import { pageMetadata } from "@/lib/site";
import { DocsButton, DocsCode, DocsHeader, DocsSection, DocsText } from "@/components/DocsUI";

export const metadata = pageMetadata(
  "/docs/pull-requests",
  "Contribute a Library | Col",
  "Prepare a focused contribution to Col, verify library metadata against official sources, and submit a pull request.",
);

export default function PullRequestsPage() {
  return (
    <article>
      <DocsHeader section="Contribute" title="Open a pull request" lead="Contributions to the directory are reviewed on GitHub." />

      <DocsSection title="Prepare your change">
        <DocsText>
          Fork the repository, create a focused branch, and keep unrelated changes out. Library additions belong in <code>data/libraries.ts</code> with a unique kebab-case slug, canonical URL, factual description, and existing taxonomy values where possible.
        </DocsText>
        <DocsText>Get Screen&apos;s agreement before starting a major feature, redesign, or adding a dependency. Keep unfinished pull requests in draft.</DocsText>
      </DocsSection>

      <DocsSection title="Update docs and discovery">
        <DocsText>Major features need usage and setup documentation linked from <code>/docs</code>. For library, component, integration, public page, or agent capability changes, verify <code>llms.txt</code>, <code>robots.txt</code>, and the sitemap. Update affected generators, page metadata, and agent guides in the same pull request. Library and integration entries are generated from catalog data.</DocsText>
      </DocsSection>

      <DocsSection title="Check your changes">
        <DocsText>Run these from the repository root before you open the pull request.</DocsText>
        <DocsCode code={"npm install\nnpm run typecheck\nnpm test"} />
        <DocsText>Tests include the production build. Check mobile layouts, light and dark modes, and keyboard access when the interface changes. Review your own diff, including any code generated by AI.</DocsText>
      </DocsSection>

      <DocsSection title="Describe it">
        <DocsText>Explain what changed, why it changed, and how you verified it. List check results and include screenshots for visible interface changes. For bug fixes, include reproduction steps and expected behavior.</DocsText>
        <DocsText>Use <code>Closes #123</code> when the PR fully resolves an issue, or <code>Refs #123</code> for a partial fix. Screen reviews and merges all pull requests and confirms issue completion after merge.</DocsText>
        <DocsButton href="https://github.com/screen-gd/Col/blob/main/CONTRIBUTING.md">Read the contribution guide</DocsButton>
      </DocsSection>
    </article>
  );
}
